/**
 * TRAVERCE — ARTISTS DATABASE (artists_db.js)
 * Auto-updated by sync_artists.js on 2026-05-21T15:22:31.887Z
 *
 * RULES:
 *  - spotify_artist_id is the PRIMARY KEY. Never change it once set.
 *  - bio_manual overrides Spotify bio. Edit via Admin Portal or directly here.
 *  - is_verified: true = synced. false = skipped, needs Admin Portal verification.
 *  - Fields below "Synced from Spotify" are overwritten on each sync — do not edit.
 */

export const ARTISTS = [
  {
    "spotify_artist_id": "6ctMiUYEAd4cy0CaH355Hk",
    "name": "Yo Maps",
    "slug": "yo-maps",
    "bio_manual": "Elton Mulenga, popularly known as Yo Maps, is one of Zambia's biggest modern music stars. Rising from humble beginnings in Lusaka, he captured national attention with the breakout hit \"Finally\" featuring Macky 2. Known for emotional love songs, smooth vocals, and intuitive storytelling, Yo Maps has built a reputation for creating music that connects deeply with everyday Zambians.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:23.238Z",
    "spotify_url": "https://open.spotify.com/artist/6ctMiUYEAd4cy0CaH355Hk",
    "genres": [],
    "followers": 152146,
    "popularity": 76,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb30574ae9b280bf3c228d4260",
    "releases": [],
    "releaseCount": 0,
    "bio": "Elton Mulenga, popularly known as Yo Maps, is one of Zambia's biggest modern music stars. Rising from humble beginnings in Lusaka, he captured national attention with the breakout hit \"Finally\" featuring Macky 2. Known for emotional love songs, smooth vocals, and intuitive storytelling, Yo Maps has built a reputation for creating music that connects deeply with everyday Zambians."
  },
  {
    "spotify_artist_id": "26fSO7cYQ1Txtb8xNi8byv",
    "name": "Chef 187",
    "slug": "chef-187",
    "bio_manual": "Chef 187, born Chimwemwe Kalota, is widely respected as one of Zambia's greatest lyricists. With sharp wordplay, intelligent punch lines, and deep storytelling, he became a household name in Zambian hip hop. His music addresses social issues while maintaining relatable experiences, earning him admiration from both fans and fellow artists.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:25.306Z",
    "spotify_url": "https://open.spotify.com/artist/26fSO7cYQ1Txtb8xNi8byv",
    "genres": [],
    "followers": 30954,
    "popularity": 15,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb35d3d42c31b022366a7fc9cc",
    "releases": [],
    "releaseCount": 0,
    "bio": "Chef 187, born Chimwemwe Kalota, is widely respected as one of Zambia's greatest lyricists. With sharp wordplay, intelligent punch lines, and deep storytelling, he became a household name in Zambian hip hop. His music addresses social issues while maintaining relatable experiences, earning him admiration from both fans and fellow artists."
  },
  {
    "spotify_artist_id": "3iBJAU4xa7sV1W9ZJO7uzK",
    "name": "KB",
    "slug": "kb",
    "bio_manual": "KB is a singer, producer, and founder of Afro Music known for modern Afro-fusion and emotionally rich songwriting. He is respected for both his artistry and production work.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:27.418Z",
    "spotify_url": "https://open.spotify.com/artist/3iBJAU4xa7sV1W9ZJO7uzK",
    "genres": [],
    "followers": 26312,
    "popularity": 13,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb1b2ef9c4fb5a24ae95e0e954",
    "releases": [],
    "releaseCount": 0,
    "bio": "KB is a singer, producer, and founder of Afro Music known for modern Afro-fusion and emotionally rich songwriting. He is respected for both his artistry and production work."
  },
  {
    "spotify_artist_id": "2rtXAAlmUadQoZk7iXi4Fe",
    "name": "Triple M",
    "slug": "triple-m",
    "bio_manual": "Triple M is a rising rapper recognized for emotional lyrics, melodic rap flows, and relatable storytelling that resonates strongly with young listeners.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:29.565Z",
    "spotify_url": "https://open.spotify.com/artist/2rtXAAlmUadQoZk7iXi4Fe",
    "genres": [],
    "followers": 22214,
    "popularity": 11,
    "portrait": "https://i.scdn.co/image/ab67616d0000b2730b29c6344c37a83c0e549aef",
    "releases": [],
    "releaseCount": 0,
    "bio": "Triple M is a rising rapper recognized for emotional lyrics, melodic rap flows, and relatable storytelling that resonates strongly with young listeners."
  },
  {
    "spotify_artist_id": "2ApKRJV8pKnEiq10xlTYTJ",
    "name": "JC Kalinks",
    "slug": "jc-kalinks",
    "bio_manual": "JC Kalinks is an energetic singer and performer whose music blends Afrobeat, dancehall, and local Zambian sounds into a youthful modern style.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:31.777Z",
    "spotify_url": "https://open.spotify.com/artist/2ApKRJV8pKnEiq10xlTYTJ",
    "genres": [],
    "followers": 20495,
    "popularity": 10,
    "portrait": "https://i.scdn.co/image/ab67616d0000b273c36325ad667a3031cd18db6f",
    "releases": [],
    "releaseCount": 0,
    "bio": "JC Kalinks is an energetic singer and performer whose music blends Afrobeat, dancehall, and local Zambian sounds into a youthful modern style."
  },
  {
    "spotify_artist_id": "3s9441fVkfNQrHBmXRFMWM",
    "name": "Kanina Kandalama",
    "slug": "kanina-kandalama",
    "bio_manual": "Kanine Kandalama is a bold female rapper known for confident delivery, youthful energy, and strong presence in Zambia's modern hip hop scene.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:33.953Z",
    "spotify_url": "https://open.spotify.com/artist/3s9441fVkfNQrHBmXRFMWM",
    "genres": [],
    "followers": 2195,
    "popularity": 1,
    "portrait": "https://i.scdn.co/image/ab67616d0000b273b7ca5a19773363b5e4ab8284",
    "releases": [],
    "releaseCount": 0,
    "bio": "Kanine Kandalama is a bold female rapper known for confident delivery, youthful energy, and strong presence in Zambia's modern hip hop scene."
  },
  {
    "spotify_artist_id": "3aufVL9SkQwm5GVFydc1GG",
    "name": "F Jay",
    "slug": "f-jay",
    "bio_manual": "F Jay is a singer and songwriter celebrated for smooth R&B vocals and emotionally driven Afro-pop music.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:36.057Z",
    "spotify_url": "https://open.spotify.com/artist/3aufVL9SkQwm5GVFydc1GG",
    "genres": [],
    "followers": 8121,
    "popularity": 4,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb28f394a111659c28258cdc00",
    "releases": [],
    "releaseCount": 0,
    "bio": "F Jay is a singer and songwriter celebrated for smooth R&B vocals and emotionally driven Afro-pop music."
  },
  {
    "spotify_artist_id": "4fLTbvnsLjg1PHp1oEiWxl",
    "name": "Chewe",
    "slug": "chewe",
    "bio_manual": "Chewe is a Zambian singer and songwriter known for contemporary Afro-pop music, youthful creativity, and smooth melodic sounds.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:38.169Z",
    "spotify_url": "https://open.spotify.com/artist/4fLTbvnsLjg1PHp1oEiWxl",
    "genres": [],
    "followers": 16710,
    "popularity": 8,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb43a3a59cf3ecb69f3d42964a",
    "releases": [],
    "releaseCount": 0,
    "bio": "Chewe is a Zambian singer and songwriter known for contemporary Afro-pop music, youthful creativity, and smooth melodic sounds."
  },
  {
    "spotify_artist_id": "2cm1BTICMJaTYi6OpPchTm",
    "name": "Rustar",
    "slug": "rustar",
    "bio_manual": "Rustar is a Zambian artist recognized for energetic performances, youthful consistency, and modern Afro-fusion music influenced by contemporary street culture.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:40.281Z",
    "spotify_url": "https://open.spotify.com/artist/2cm1BTICMJaTYi6OpPchTm",
    "genres": [],
    "followers": 12526,
    "popularity": 6,
    "portrait": "https://i.scdn.co/image/ab6761610000e5ebfc98497bf51e37c2ec55f57d",
    "releases": [],
    "releaseCount": 0,
    "bio": "Rustar is a Zambian artist recognized for energetic performances, youthful consistency, and modern Afro-fusion music influenced by contemporary street culture."
  },
  {
    "spotify_artist_id": "5f24U3gtxTUPIRT2HujkHm",
    "name": "Xaven",
    "slug": "xaven",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:44.010Z",
    "spotify_url": "https://open.spotify.com/artist/5f24U3gtxTUPIRT2HujkHm",
    "genres": [],
    "followers": 30568,
    "popularity": 15,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb6fec472f436f3da068ad5a63",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "1S4KltOEUKNdbOd9RrI5Lg",
    "name": "Mordecaii",
    "slug": "mordecaii",
    "bio_manual": "Mordecaii is a youthful singer and songwriter admired for emotional vocals, smooth melodies, and heartfelt songwriting.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:46.153Z",
    "spotify_url": "https://open.spotify.com/artist/1S4KltOEUKNdbOd9RrI5Lg",
    "genres": [],
    "followers": 18054,
    "popularity": 9,
    "portrait": "https://i.scdn.co/image/ab6761610000e5ebf8abff958f1d2f1ba58db4e8",
    "releases": [],
    "releaseCount": 0,
    "bio": "Mordecaii is a youthful singer and songwriter admired for emotional vocals, smooth melodies, and heartfelt songwriting."
  },
  {
    "spotify_artist_id": "4O9BYjQLNhndddq00X0ALc",
    "name": "The F.A.K.E",
    "slug": "the-f-a-k-e",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:50.230Z",
    "spotify_url": "https://open.spotify.com/artist/4O9BYjQLNhndddq00X0ALc",
    "genres": [],
    "followers": 7992,
    "popularity": 3,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb127f21f5dd91c0b4b1820be4",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "1CGpjhbMNattNmUtBaj31Q",
    "name": "Styve Ace",
    "slug": "styve-ace",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:53.003Z",
    "spotify_url": "https://open.spotify.com/artist/1CGpjhbMNattNmUtBaj31Q",
    "genres": [],
    "followers": 3482,
    "popularity": 1,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb1d88d78630bd5fc2b179d693",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "6T36EOpJj9B6SnyynRqpgG",
    "name": "Bad boy shezy",
    "slug": "bad-boy-shezy",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:55.997Z",
    "spotify_url": "https://open.spotify.com/artist/6T36EOpJj9B6SnyynRqpgG",
    "genres": [],
    "followers": 376,
    "popularity": 0,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb815485b84d210ed0e54455ba",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "4OKrofOC9Ypgu1HBxZIMb0",
    "name": "Iamwaters",
    "slug": "iamwaters",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:21:58.852Z",
    "spotify_url": "https://open.spotify.com/artist/4OKrofOC9Ypgu1HBxZIMb0",
    "genres": [],
    "followers": 604,
    "popularity": 0,
    "portrait": "https://i.scdn.co/image/ab67616d0000b273d4205eae2546d89979ae9d6e",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "2Ek5746GXl1ePTgpFBnbct",
    "name": "Nyarai",
    "slug": "nyarai",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": null,
    "spotify_url": "https://open.spotify.com/artist/2Ek5746GXl1ePTgpFBnbct",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "4GbzyoLPE0z6jvL5h9st3F",
    "name": "VLEKO",
    "slug": "vleko",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:04.889Z",
    "spotify_url": "https://open.spotify.com/artist/4GbzyoLPE0z6jvL5h9st3F",
    "genres": [],
    "followers": 11,
    "popularity": 0,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb809cc3aa3d98f55b91f3ea1d",
    "releases": [],
    "releaseCount": 0,
    "bio": "Gideon Emery (born September 12, 1972) is an English actor. He is best known for his role as Deucalion in Teen Wolf and starring as himself in Call of Duty: Advanced Warfare. His career also includes providing voice-over work in video games, television series and films, notably as Fenris in Dragon Age II."
  },
  {
    "spotify_artist_id": "4zefLiC0h0euXegWWgGq3p",
    "name": "Zaggar",
    "slug": "zaggar",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:07.905Z",
    "spotify_url": "https://open.spotify.com/artist/4zefLiC0h0euXegWWgGq3p",
    "genres": [],
    "followers": 695,
    "popularity": 0,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb90c4fc40c38889ad3b843cd4",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "44vOrGC9wQuBCQIeBUNc1O",
    "name": "Tio Nason",
    "slug": "tio-nason",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:11.077Z",
    "spotify_url": "https://open.spotify.com/artist/44vOrGC9wQuBCQIeBUNc1O",
    "genres": [],
    "followers": 19316,
    "popularity": 9,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb647e80f7fce106ed6a9b6d70",
    "releases": [],
    "releaseCount": 0,
    "bio": "Victoria Wezi Mhone (born 25 May 1992), known in music circles as Wezi or Wezi HeartSound, is a Zambian singer and songwriter. She rose to fame in 2016 after releasing her debut EP Uhai which won her the 2016 new artist of the year at the Zambia Music Awards."
  },
  {
    "spotify_artist_id": "4Un29hGNtmUOCCGQWiInis",
    "name": "Esii",
    "slug": "esii",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:14.294Z",
    "spotify_url": "https://open.spotify.com/artist/4Un29hGNtmUOCCGQWiInis",
    "genres": [],
    "followers": 14683,
    "popularity": 7,
    "portrait": "https://i.scdn.co/image/ab67616d0000b27342a52402eca83ee8babd8b99",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "5Y8PQZPxzdPxPqGxoqKC5H",
    "name": "Frank Ro",
    "slug": "frank-ro",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:17.059Z",
    "spotify_url": "https://open.spotify.com/artist/5Y8PQZPxzdPxPqGxoqKC5H",
    "genres": [],
    "followers": 50394,
    "popularity": 25,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eba59b6fea7e39b132f0b071f9",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "0j5CGslS41MUjK6uekSHZU",
    "name": "Mag44",
    "slug": "mag44",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:19.916Z",
    "spotify_url": "https://open.spotify.com/artist/0j5CGslS41MUjK6uekSHZU",
    "genres": [],
    "followers": 13496,
    "popularity": 6,
    "portrait": "https://i.scdn.co/image/ab67616d0000b273ba62339b3499ede4c6e62852",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "0uAUrmEQbwcDFzg0v7VicO",
    "name": "Lila Iké",
    "slug": "lila-ik-",
    "bio_manual": "Lila Iké (born Alecia Tameka Grey; January 23, 1994) is a Jamaican reggae singer and songwriter. After releasing multiple singles, Iké released her debut EP The ExPerience in May 2020. Her debut album Treasure Self Love, released in August 2025, was nominated for a Grammy in the Reggae category. She performed at the 2026 Grammy Awards.",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:21.957Z",
    "spotify_url": "https://open.spotify.com/artist/0uAUrmEQbwcDFzg0v7VicO",
    "genres": [],
    "followers": 244795,
    "popularity": 100,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb6de796bfe7d55b72adb3337b",
    "releases": [],
    "releaseCount": 0,
    "bio": "Lila Iké (born Alecia Tameka Grey; January 23, 1994) is a Jamaican reggae singer and songwriter. After releasing multiple singles, Iké released her debut EP The ExPerience in May 2020. Her debut album Treasure Self Love, released in August 2025, was nominated for a Grammy in the Reggae category. She performed at the 2026 Grammy Awards."
  },
  {
    "spotify_artist_id": "0rskhjcLm5BxjwZDRs4142",
    "name": "Magixx",
    "slug": "magixx",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:25.484Z",
    "spotify_url": "https://open.spotify.com/artist/0rskhjcLm5BxjwZDRs4142",
    "genres": [],
    "followers": 572308,
    "popularity": 100,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb7ac2f480f0edc357026b1844",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "16rCzZOMQX7P8Kmn5YKexI",
    "name": "Mahalia",
    "slug": "mahalia",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:28.452Z",
    "spotify_url": "https://open.spotify.com/artist/16rCzZOMQX7P8Kmn5YKexI",
    "genres": [],
    "followers": 902350,
    "popularity": 100,
    "portrait": "https://i.scdn.co/image/ab6761610000e5ebbffc1b26ed2fd56ae2d569fd",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": "3ukrG1BmfEiuo0KDj8YTTS",
    "name": "Teni",
    "slug": "teni",
    "bio_manual": "",
    "is_verified": true,
    "last_synced_at": "2026-05-21T15:22:31.349Z",
    "spotify_url": "https://open.spotify.com/artist/3ukrG1BmfEiuo0KDj8YTTS",
    "genres": [],
    "followers": 790497,
    "popularity": 100,
    "portrait": "https://i.scdn.co/image/ab6761610000e5eb30fc3de1a76490e2b4b53569",
    "releases": [],
    "releaseCount": 0,
    "bio": ""
  },
  {
    "spotify_artist_id": null,
    "name": "Macky 2",
    "slug": "macky-2",
    "bio_manual": "Macky 2, born Mulaza Kaira, is one of the most influential figures in Zambian entertainment. Beyond music, he is known for mentoring young talent, building Alpha entertainment, and helping shape modern Zambian hip hop. His journey from the Copperbelt to national fame continues to inspire many upcoming creatives.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "5odh0PSm1oW63rQQ40rQKp2",
    "name": "Chile One Mr Zambia",
    "slug": "chile-one-mr-zambia",
    "bio_manual": "Chile One Mr Zambia is a singer and songwriter known for heartfelt music that speaks about love, pain, relationships, and everyday struggles. His emotional and relatable lyrics quickly made him one of Zambia's most streamed and loved artists.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "2FLkXn6ok1U2w6djStuOko",
    "name": "Slapded",
    "slug": "slapded",
    "bio_manual": "Slapded, born Mwila Mussonda, is regarded as one of the pioneers of Zambian hip hop. As founder of XYZ Entertainment, he played a huge role in developing some of Zambia's biggest music stars. His influence stretches beyond hip hop into business, talent development, and entertainment leadership.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "2LSlm5f7YRrw7wV8rX4XPs",
    "name": "Jae Cash",
    "slug": "jae-cash",
    "bio_manual": "Jae Cash is a respected rapper and storyteller whose music often reflects street life, ambition, loyalty, and personal growth. Through Afro hip hop to Afrobeats, he has built both a successful music career and a platform for nurturing upcoming artists.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "4ADVuenhDMxENJiFOJD3CYG",
    "name": "Jemax",
    "slug": "jemax",
    "bio_manual": "Jemax is known for authentic storytelling, socially conscious lyrics, and energetic performances. His rise from the underground rap scene into mainstream success has made him one of Zambia's most respected hip hop voices.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "3iN1UoVLL8XNoI4WKZACGiP",
    "name": "T-Sean",
    "slug": "t-sean",
    "bio_manual": "T-Sean is a versatile singer, producer, and songwriter known for blending dancehall, reggae, and Afro-pop into a unique Zambian sound. Over the years, he has become known not only for his hit songs but also for discovering and supporting emerging talent.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": null,
    "name": "Roberto",
    "slug": "roberto",
    "bio_manual": "Roberto, born Robert Banda, is a Zambian Afro-pop and R&B artist known for smooth vocals, international collaborations, and chart-topping songs. His music combines African rhythms with modern pop influences, helping him gain recognition across the continent.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": null,
    "name": "Chanda Na Kay",
    "slug": "chanda-na-kay",
    "bio_manual": "Chanda Na Kay is one of Zambia's most energetic music duos, known for catchy street anthems, humor, and relatable youth culture. Their music reflects everyday life on the Copperbelt and resonates strongly with younger audiences.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "4n0mSrU8r8UA6AQMOODiAKi",
    "name": "Towela",
    "slug": "towela",
    "bio_manual": "Towela is a Zambian singer and songwriter admired for her soft vocals, emotional songwriting, and elegant Afro-pop sound. She has steadily built a strong presence in Zambia's music scene through collaborations and solo releases.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "4yeGmqfRB97HFk971vUIb0",
    "name": "Bombshell Grenade",
    "slug": "bombshell-grenade",
    "bio_manual": "Bombshell Grenade is known for her bold personality, confident rap style, and fearless approach to female empowerment in music. She remains one of Zambia's most recognized female hip hop artists.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "22Ai51CSD818ua6iJf1T72",
    "name": "Mampi",
    "slug": "mampi",
    "bio_manual": "Mampi is famous for her electrifying stage performances and dancehall-inspired Afro-pop hits. Her energetic style and charisma helped her become one of Zambia's most recognizable female entertainers.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "15ymdzp3d5AwqdRAxcXsLIG",
    "name": "Bobby East",
    "slug": "bobby-east",
    "bio_manual": "Bobby East is a rapper, actor, and songwriter known for his versatility, creativity, and influence on modern Zambian entertainment. His music and personality has a lasting impact on fans across the country.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "31gtAPiSr54fYpzruTsi25",
    "name": "Rich Bizzy",
    "slug": "rich-bizzy",
    "bio_manual": "Rich Bizzy is known for high energy music, vibrant performances, and songs that dominate local celebrations and dance floors. His playful style and catchy hooks have made him a fan favorite.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "3CiINqa8I08nutZileDaIwu",
    "name": "Afuika",
    "slug": "afuika",
    "bio_manual": "Afuika is celebrated for preserving and modernizing Kalindula-inspired music. His songs often reflect Zambian culture, traditions, and everyday experiences.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "2mCAbnKz2NzpIEUSNVqJw0",
    "name": "B Flow",
    "slug": "b-flow",
    "bio_manual": "B Flow is an Afro-pop artist and activist known for using music to address social issues, youth empowerment, and positive change. His influence extends beyond entertainment into advocacy work across Africa.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "0NouFRAPJf08aPiN9k0d9Z",
    "name": "Neo Long",
    "slug": "neo-long",
    "bio_manual": "Neo Long is a melodic rapper known for emotional storytelling and versatile delivery. His music blends contemporary hip hop with modern Afro influences.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "7yONV5kZtnuFEkdE1ojI5v",
    "name": "Drifta Trek",
    "slug": "drifta-trek",
    "bio_manual": "Drifta Trek is recognized for hard-hitting rap lyrics, confidence, and strong Copperbelt influence. He remains one of Zambia's most respected hip hop voices.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "5Tp5IoeSwZ2WmJa4fvs7Gs",
    "name": "Cleo Ice Queen",
    "slug": "cleo-ice-queen",
    "bio_manual": "Cleo Ice Queen is a rapper, entrepreneur, and media personality who helped open doors for female artists in Zambia's hip hop industry. Her confidence and creativity continue to inspire aspiring young women.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "2F9vDmoE0KMQePoilUXwr8",
    "name": "Ruff Kid",
    "slug": "ruff-kid",
    "bio_manual": "Ruff Kid is known for lyrical rap music, energetic delivery, and his contribution to Zambia's hardcore hip hop scene.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "1rkz7wbdg2BwBCN6TSftKU",
    "name": "Pompi",
    "slug": "pompi",
    "bio_manual": "Pompi is one of Zambia's leading gospel artists, celebrated for blending inspirational messages with Afro-pop, reggae, and contemporary African sounds.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "2wMANrIhcgfmu0NQNcBhm0",
    "name": "Esther Chungu",
    "slug": "esther-chungu",
    "bio_manual": "Esther Chungu is a gospel singer and worship leader admired for her powerful voice, uplifting music, and inspirational performances.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "7uiY662mu3r7kmvMWg0753",
    "name": "Muzo AKA Alphonso",
    "slug": "muzo-aka-alphonso",
    "bio_manual": "Muzo AKA Alphonso is known for raw storytelling, socially conscious rap, and music that reflects real-life struggles and street experiences.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "01spx1OrZ5MxCjAxWU749F",
    "name": "Y Celeb",
    "slug": "y-celeb",
    "bio_manual": "Y Celeb is a street music sensation known for energetic performances, bold personality, and strong influence within Zambia's urban culture.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "7FKacanYJy6Z6ftNbVWMC1",
    "name": "Vinchenzo",
    "slug": "vinchenzo",
    "bio_manual": "Vinchenzo is loved for catchy Afro-pop music, humorous storytelling, and songs that capture relatable Zambian experiences.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "7qQTIFEvoM8rO3YfF388SCn",
    "name": "76 Drums",
    "slug": "76-drums",
    "bio_manual": "76 Drums is a producer and artist known for shaping modern Zambian Afrobeat sounds through high-quality production and creative collaborations.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "0ALMcQV83GQ2ik7klHBOGk",
    "name": "Dismo",
    "slug": "dismo",
    "bio_manual": "Dismo is one of Zambia's most talked-about modern rappers, known for emotional storytelling, street-inspired music, and a passionate fan base.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "4fTJuju8DV2fDvimriRN5I",
    "name": "Kay Figo",
    "slug": "kay-figo",
    "bio_manual": "Kay Figo is a singer, dancer, and entertainer recognized for vibrant performances, Afro-pop music, and strong stage presence.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "0yjc53eDlzK09GhondKugz",
    "name": "Shanky Stringah",
    "slug": "shanky-stringah",
    "bio_manual": "Shanky Stringah is a singer, producer, and songwriter known for autofiy Afro-pop hits and his contribution behind the scenes as a music producer.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "1OnCFDkaebZV21oPukeOq0",
    "name": "Blood Kid",
    "slug": "blood-kid",
    "bio_manual": "Blood Kid is a rapper known for energetic flows, street-inspired music, and a fearless approach to modern Zambian hip hop.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "58OpcTPjLo8dAYU1oWM8i7",
    "name": "D Bwoy",
    "slug": "d-bwoy",
    "bio_manual": "D Bwoy is a singer and songwriter recognized for Afro-pop music, relatable storytelling, and collaborations with major Zambian artists.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "3kn4gP2yKGioiWXiJupa1T",
    "name": "Mumba Yachi",
    "slug": "mumba-yachi",
    "bio_manual": "Mumba Yachi is a cultural artist and musician known for blending traditional African sounds with modern music influences while celebrating Zambian heritage.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "74us4icTOQzxUsaai8Ls3H",
    "name": "Wazi",
    "slug": "wazi",
    "bio_manual": "Wazi is admired for soulful vocals, poetic songwriting, and music that speaks about love, society, and personal experiences.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "59oLXWtabRJshYSqK6IOjw",
    "name": "Natasha Chansa",
    "slug": "natasha-chansa",
    "bio_manual": "Natasha Chansa is a rapper and performer known for fearless flows, confidence, and promoting female empowerment in music.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "3kbalKkrzFLiOrNe9KC9mp",
    "name": "Urban Hype",
    "slug": "urban-hype",
    "bio_manual": "Urban Hype is a music group known for modern Afro-pop, Afro-romance, and urban music that gained popularity among younger audiences.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "7NIxTMqTyEluklaCRQ6SL0",
    "name": "Dope Boys",
    "slug": "dope-boys",
    "bio_manual": "Dope Boys are known for street music, entertaining performances, and songs that capture everyday life and Zambian street culture.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "4WzzJo60jU0oOG0pMrfZW0",
    "name": "Daev Zambia",
    "slug": "daev-zambia",
    "bio_manual": "Daev Zambia was a talented singer and songwriter remembered for emotional music, inspirational messages, and his positive impact on Zambia's music scene.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "9z0t51B7027gi2vLtoXQCk",
    "name": "El Mukuka",
    "slug": "el-mukuka",
    "bio_manual": "El Mukuka is a Zambia-born DJ, producer, and songwriter known for Afro-house music, electronic sounds, and international collaborations that blended African rhythms with global dance music.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "3JytWat2EIUTwEiGTClY0I",
    "name": "Kaya Adams",
    "slug": "kaya-adams",
    "bio_manual": "Kaya Adams is a Zambian singer and songwriter known for Afro-pop melodies, emotionally driven music, and modern contemporary sounds that resonate with younger audiences.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "2eGiZwVEiT8xnmFjrQ2tA0",
    "name": "Neo",
    "slug": "neo",
    "bio_manual": "Neo is a Zambian singer and songwriter known for emotional love songs, soulful vocals, and relatable storytelling that has earned him a loyal fan base across Zambia.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "40xtwRaCZE8BopNxCietVI",
    "name": "TBwoy",
    "slug": "tbwoy",
    "bio_manual": "TBwoy is a Zambian singer and songwriter known for Afro-pop and dancehall-inspired music, catchy hooks, and collaborations with some of Zambia's leading artists.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "04avofIwqNDbQav7PhPNzL",
    "name": "Kaladoshas",
    "slug": "kaladoshas",
    "bio_manual": "Kaladoshas is a Zambian rapper and songwriter known for lyrical hip hop, motivational music, and strong influence within Zambia's urban music scene.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "0kl0mA5SqJjMsaqeZhvbUp",
    "name": "Nalu",
    "slug": "nalu",
    "bio_manual": "Nalu is a Zambian singer and songwriter admired for soulful vocals, emotional songwriting, and modern Afro-pop sounds.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "6lmCOtb0XGLiUEWs0cdAoF",
    "name": "Willz Mr Nyopole",
    "slug": "willz-mr-nyopole",
    "bio_manual": "Willz Mr Nyopole is a Zambian rapper and songwriter recognized for stylish delivery, confident rap music, and influential urban culture presence.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "1pc73Bxyad8pynu1rksmlc",
    "name": "Izrael",
    "slug": "izrael",
    "bio_manual": "Izrael is a Zambian singer and songwriter known for emotional music, unique vocal delivery, and inspirational storytelling.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "2YcJC1hnLjOIvNN3naeAlG",
    "name": "Jay Rox",
    "slug": "jay-rox",
    "bio_manual": "Jay Rox is a Zambian rapper, producer, and entrepreneur known for innovative music production and his contribution to shaping Zambia's modern urban sound.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "6OipLN8VbfUtRF75sJdndw",
    "name": "4 Na 5",
    "slug": "4-na-5",
    "bio_manual": "4 Na 5 is a Zambian music duo recognized for catchy street anthems, relatable storytelling, and energetic performances.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "3h7a68prjL0PuH3YyGBii2",
    "name": "Aqulaskin",
    "slug": "aqulaskin",
    "bio_manual": "Aqulaskin is a Copperbelt-based Zambian artist known for energetic street music, charismatic performances, and strong youth appeal.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "226iSW6CcS2fPJccinrU8D",
    "name": "Drimz Mr Muziq",
    "slug": "drimz-mr-muziq",
    "bio_manual": "Drimz Mr Muziq is a Zambian singer, producer, and songwriter admired for soulful vocals, romantic music, and smooth Afro-R&B production.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  },
  {
    "spotify_artist_id": "1UEbxrXVcbM69C0twEORJy",
    "name": "Ndine Emma",
    "slug": "ndine-emma",
    "bio_manual": "Ndine Emma is a Zambian comedian, content creator, and artist known for blending humor, storytelling, and music into relatable entertainment.",
    "is_verified": false,
    "last_synced_at": null,
    "spotify_url": "",
    "genres": [],
    "followers": 0,
    "popularity": 0,
    "portrait": "",
    "releases": [],
    "releaseCount": 0
  }
];
